"""
=============================================================================
Phase 7: Advanced Production Patterns - Lesson 30: Dynamic Map-Reduce with Send API
=============================================================================

Pattern:
                     START
                       │
                       ▼
                 generate_tasks  (Dynamically determines N items at runtime)
                       │
             ┌─────────┴─────────┐  (Send API: Dynamic fan-out)
             ▼         ▼         ▼
          Worker 1  Worker 2  Worker 3 ... (Runs in parallel for each item)
             └─────────┬─────────┘
                       │  (Fan-in: Reducer merges all outputs)
                       ▼
                 aggregate_results
                       │
                      END

Key Concepts:
1. Static Parallel vs. Dynamic Map-Reduce:
   - Static parallel graphs (Lesson 5) have fixed, predefined branches.
   - The `Send(node_name, sub_state)` API allows a conditional edge to fan out
     to an arbitrary, dynamic number of parallel workers determined at runtime.
2. The Send Object:
   `return [Send("analyze_topic", {"topic": t}) for t in state["topics"]]`
   spawns one independent execution of `analyze_topic` per item.
3. Aggregation:
   Downstream nodes collect results from all `Send` workers via an `operator.add`
   reducer list.
=============================================================================
"""

import sys
import io
import operator
from typing import Annotated, List
from typing_extensions import TypedDict
from langgraph.graph import StateGraph, START, END
from langgraph.constants import Send

# Ensure proper utf-8 encoding for Windows terminals
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')


# --- 1. Define State Schemas ---
# Overall graph state
class ResearchProjectState(TypedDict):
    main_subject: str
    sub_topics: List[str]
    # Reducer: all dynamically spawned workers will append their report here
    worker_reports: Annotated[List[str], operator.add]
    final_executive_summary: str


# Independent state passed to each dynamically spawned worker
class SubTopicState(TypedDict):
    topic: str


# --- 2. Define Nodes ---
def generate_tasks_node(state: ResearchProjectState) -> dict:
    print(f"\n[Task Generator] Breaking main subject '{state['main_subject']}' into dynamic sub-topics...")
    # Dynamically generated list of tasks (could be 3, 5, or 10 items)
    topics = [
        f"{state['main_subject']}: Architecture & Design",
        f"{state['main_subject']}: Security & Governance",
        f"{state['main_subject']}: Performance Benchmarks"
    ]
    for t in topics:
        print(f"  * Generated Sub-Task: {t}")
    return {"sub_topics": topics}


def worker_node(state: SubTopicState) -> dict:
    """Worker executed in parallel for EACH item generated by the Send API."""
    topic = state["topic"]
    print(f"\n  --> [Dynamic Worker] Analyzing sub-topic: '{topic}'...")
    report = f"Deep Dive Report for [{topic}]: Completed successfully with high confidence."
    return {"worker_reports": [report]}


def aggregate_results_node(state: ResearchProjectState) -> dict:
    """Collects all reports once all Send workers have completed."""
    print(f"\n[Aggregator] All dynamic workers finished! Compiling executive summary...")
    summary = (
        f"Executive Summary for '{state['main_subject']}':\n"
        f"Synthesized {len(state['worker_reports'])} sub-topic reports:\n" +
        "\n".join([f"  - {r}" for r in state["worker_reports"]])
    )
    return {"final_executive_summary": summary}


# --- 3. Dynamic Fan-Out Router using Send API ---
def map_subtopics_to_workers(state: ResearchProjectState):
    """
    Returns a list of Send objects.
    LangGraph dynamically spawns one 'worker' node per Send object!
    """
    print(f"\n[Send Router] Spawning {len(state['sub_topics'])} parallel worker nodes...")
    return [
        Send("worker", {"topic": sub_topic})
        for sub_topic in state["sub_topics"]
    ]


def main():
    print("=" * 65)
    print("  LangGraph Advanced: Lesson 30 - Dynamic Map-Reduce (Send API)")
    print("=" * 65)

    # --- 4. Assemble Graph ---
    graph = StateGraph(ResearchProjectState)

    graph.add_node("generate_tasks", generate_tasks_node)
    graph.add_node("worker", worker_node)
    graph.add_node("aggregate_results", aggregate_results_node)

    graph.add_edge(START, "generate_tasks")

    # Dynamic Fan-Out using Send:
    # Instead of pointing to a fixed node name, map_subtopics_to_workers returns
    # a list of Send("worker", SubTopicState) instances!
    graph.add_conditional_edges("generate_tasks", map_subtopics_to_workers, ["worker"])

    # All dynamic worker instances converge to aggregate_results (Fan-In)
    graph.add_edge("worker", "aggregate_results")
    graph.add_edge("aggregate_results", END)

    app = graph.compile()

    # --- 5. Run Map-Reduce ---
    initial_input: ResearchProjectState = {
        "main_subject": "Autonomous Cloud Deployments",
        "sub_topics": [],
        "worker_reports": [],
        "final_executive_summary": ""
    }

    final_state = app.invoke(initial_input)

    print("\n" + "=" * 65)
    print("Map-Reduce Execution Complete!")
    print("=" * 65)
    print(final_state["final_executive_summary"])


if __name__ == "__main__":
    main()
