from langchain_core.messages import BaseMessage
from langgraph.graph import add_messages
from typing import Annotated
from typing import TypedDict
from langgraph.graph import StateGraph, MessagesState, START, END
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from langchain_core.messages import HumanMessage, AIMessage
from langgraph.checkpoint.memory import MemorySaver
from dotenv import load_dotenv
load_dotenv()

# 1. Initialize the Model
endpoint = HuggingFaceEndpoint(
    repo_id="deepseek-ai/DeepSeek-V4-Pro",
    task="text-generation",
    max_new_tokens=512,
    temperature=0.7,
)
llm = ChatHuggingFace(llm=endpoint)

# 2. Define State
class ChatState(TypedDict):
    """Simple state for a chatbot: just the list of messages"""
    messages: Annotated[list[BaseMessage], add_messages]

# 3. Define the Node Logic
def chatbot_node(state: ChatState) -> dict:
    """Takes the list of messages and returns the next AI response."""
    messages = state["messages"]
    
    # The LLM handles the conversation logic
    response = llm.invoke(messages)
    # print(f"\n\n\n\nAI Response : {response}")
    
    # Append the response to the state
    return {"messages": [response]}

# 4. Add Checkpointer/ memory part of the conversation
checkpoint_saver = MemorySaver() # for checkpointing, we need to pass this object

# 5. Build the Graph
graph_builder = StateGraph(ChatState)

# Add the node and edges
graph_builder.add_node("chatbot", chatbot_node)
graph_builder.add_edge(START, "chatbot")
graph_builder.add_edge("chatbot", END)

# Compile the graph
app = graph_builder.compile(checkpointer=checkpoint_saver)

# 6. Test the Chatbot
if __name__ == "__main__":
    print("--- Simple LangGraph Chatbot ---")
    print("Enter 'quit' to exit.")
    thread_id = "thread_1"
    
    while True:
        user_input = input("\nYou: ").strip()
        if user_input.lower() == "quit":
            break
        if not user_input:
            continue
        
        # Display thinking status
        print("Bot: Thinking...", end="", flush=True)
        first_token = True
        full_response = ""
        config = {"configurable": {"thread_id": thread_id}} # gives unique ID to the conversation
        
        # stream_mode="messages" streams tokens as they are generated by the LLM
        events = app.stream(
            {"messages": [HumanMessage(content=user_input)]}, 
            stream_mode="messages", # for streaming, we need to pass this mode
            config=config # for checkpointing, we need to pass this config
        )
        
        for msg_chunk, metadata in events:
            # Filter only chunks coming from the chatbot node that contain content
            if metadata.get("langgraph_node") == "chatbot" and msg_chunk.content:
                if first_token:
                    # Clear "Thinking..." and prepare for bot response
                    print("\rBot: " + " " * 20 + "\rBot: ", end="", flush=True)
                    first_token = False
                print(msg_chunk.content, end="", flush=True)
                full_response += msg_chunk.content
        
        if first_token:
            print("\rBot: (No response generated)")
        else:
            print()

    print("\n--- Conversation Ended ---")