import os
import sys
import io
from dotenv import load_dotenv
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from langchain_core.tools import tool
from langchain_core.messages import ToolMessage, AIMessage

# Configure standard output to use UTF-8 encoding (prevents Windows terminal encoding errors)
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Load environment variables
load_dotenv()

# --- 1. Define custom tools ---

@tool
def get_current_weather(location: str) -> str:
    """Use this tool to get the current weather and temperature for a specific city location.
    The input parameter 'location' must be a city name (e.g. 'Paris', 'London')."""
    print(f"\n[Tool Invoked: get_current_weather] Running weather lookup for: '{location}'...")
    return f"The weather in {location} is currently 22 degrees and sunny."

@tool
def add_numbers(a: int, b: int) -> int:
    """Use this tool to add two numbers together.
    Inputs must be integers."""
    print(f"\n[Tool Invoked: add_numbers] Adding numbers: {a} + {b}...")
    return a + b

def main():
    # Check for Hugging Face token
    huggingface_token = os.environ.get("HUGGINGFACEHUB_API_TOKEN")
    if not huggingface_token:
        print("ERROR: HUGGINGFACEHUB_API_TOKEN not found in environment. Please check your .env file.")
        return

    # --- 2. Initialize LLM and Chat Model wrapper ---
    print("Initializing API-based Hugging Face Chat LLM...")
    llm = HuggingFaceEndpoint(
        repo_id="deepseek-ai/DeepSeek-V4-Pro",
        task="text-generation",
        max_new_tokens=512,
        temperature=0.1,  # Lower temperature is critical for structured tool calling
        huggingfacehub_api_token=huggingface_token
    )
    chat_model = ChatHuggingFace(llm=llm)

    # --- 3. Bind tools to the Chat Model ---
    tools = [get_current_weather, add_numbers]
    model_with_tools = chat_model.bind_tools(tools)
    print("Tools bound successfully!")

    # Query requires calling BOTH tools
    query = "What is the weather in Paris, and what is the sum of 123 and 456?"
    print(f"\n=== Target Query: '{query}' ===")

    try:
        # --- Stage 1: Send initial query to Chat Model ---
        print("\n--- STAGE 1: Initial LLM Query ---")
        messages = [("user", query)]
        response = model_with_tools.invoke(messages)
        
        print("\n=== First AI Response (Tool Call Generation) ===")
        print(response)
        
        # If model generated tool calls, execute them
        if response.tool_calls:
            messages.append(response)
            
            # --- Stage 2: Loop and execute tools locally ---
            print("\n--- STAGE 2: Tool Execution Loop ---")
            tools_map = {t.name: t for t in tools}
            
            for tool_call in response.tool_calls:
                t_name = tool_call["name"]
                t_args = tool_call["args"]
                t_id = tool_call["id"]
                
                # Fetch tool and execute it locally
                tool_obj = tools_map[t_name]
                print(f"Executing tool '{t_name}' with arguments: {t_args}...")
                result = tool_obj.invoke(t_args)
                print(f"Tool Result: '{result}'")
                
                # Construct ToolMessage wrapping the result and linking the tool_call_id
                tool_msg = ToolMessage(content=str(result), tool_call_id=t_id)
                messages.append(tool_msg)
            
            # --- Stage 3: Send back history with ToolMessages to LLM ---
            print("\n--- STAGE 3: Final LLM Generation (Feedback Loop) ---")
            print("Message history to send to LLM:")
            for msg in messages:
                print(f"  - {msg.__class__.__name__}: {getattr(msg, 'content', '') or getattr(msg, 'tool_calls', '')}")
                
            final_response = model_with_tools.invoke(messages)
            
            print("\n=== Final AI Response (Synthesized Answer) ===")
            print(final_response.content)
        else:
            print("\nNo tool calls generated by the model. Response:")
            print(response.content)
            
    except Exception as e:
        print(f"\n[API Call Failed: {e}]")
        print("\n=== Running Simulated Dry-Run Tool Calling Loop ===")
        print("To illustrate the data flow, we will simulate the model's tool calls and execute the tools locally.\n")
        
        # 1. Simulated first response from the LLM containing tool calls
        simulated_tool_calls = [
            {
                "name": "get_current_weather",
                "args": {"location": "Paris"},
                "id": "call_weather_mock_123"
            },
            {
                "name": "add_numbers",
                "args": {"a": 123, "b": 456},
                "id": "call_add_mock_456"
            }
        ]
        simulated_response = AIMessage(content="", tool_calls=simulated_tool_calls)
        
        print("--- STAGE 1: (Simulated) Initial LLM Query ---")
        print(f"User: '{query}'")
        print(f"AI Output Tool Calls: {simulated_response.tool_calls}")
        
        # Setup conversation history
        messages = [("user", query), simulated_response]
        
        # 2. Executing the tools locally and wrapping in ToolMessages
        print("\n--- STAGE 2: (Actual) Tool Execution Loop ---")
        tools_map = {t.name: t for t in tools}
        
        for tool_call in simulated_response.tool_calls:
            t_name = tool_call["name"]
            t_args = tool_call["args"]
            t_id = tool_call["id"]
            
            # Execute tool locally
            tool_obj = tools_map[t_name]
            result = tool_obj.invoke(t_args)
            
            # Construct ToolMessage linking the unique tool_call_id
            tool_msg = ToolMessage(content=str(result), tool_call_id=t_id)
            print(f"Executed tool '{t_name}' with args {t_args} -> Result: '{result}'")
            print(f"Created ToolMessage: {tool_msg}\n")
            messages.append(tool_msg)
            
        # 3. Final Step representation
        print("--- STAGE 3: (Simulated) Final LLM Generation ---")
        print("Message history compiled for feedback:")
        for msg in messages:
            type_name = msg.__class__.__name__ if not isinstance(msg, tuple) else "UserTuple"
            content_val = getattr(msg, 'content', '') or getattr(msg, 'tool_calls', '') if not isinstance(msg, tuple) else msg[1]
            print(f"  - {type_name}: {content_val}")
            
        print("\n=== Final AI Response (Simulated Synthesis) ===")
        print("Based on the tools, the weather in Paris is currently 22 degrees and sunny, and the sum of 123 and 456 is 579.")

if __name__ == "__main__":
    main()
