/**
 * ============================================================================
 * LangChain.js - Lesson 1: Prompts & Chat Models
 * ============================================================================
 * Key Concepts:
 * 1. Messages: HumanMessage, AIMessage, SystemMessage represent roles.
 * 2. ChatPromptTemplate: Reusable blueprints with dynamic placeholder variables.
 * 3. Model Invocation: Passing formatted prompt values into chat models.
 * ============================================================================
 */

import {
  ChatPromptTemplate,
  SystemMessagePromptTemplate,
  HumanMessagePromptTemplate,
} from "@langchain/core/prompts";
import { HumanMessage, AIMessage, SystemMessage } from "@langchain/core/messages";

// --- 1. Pure Messages Array ---
const rawMessages = [
  new SystemMessage("You are a helpful culinary chef."),
  new HumanMessage("What can I substitute for eggs in baking?"),
];

console.log("Raw System Message:", rawMessages[0].content);
console.log("Raw Human Message :", rawMessages[1].content);

// --- 2. ChatPromptTemplate with Dynamic Variables ---
const promptTemplate = ChatPromptTemplate.fromMessages([
  ["system", "You are an expert translator specializing in {domain} terminology."],
  ["user", "Translate the following text into {targetLanguage}: '{textToTranslate}'"],
]);

async function main() {
  console.log("=".repeat(65));
  console.log("  LangChain.js Lesson 1: Prompts & Message Templates");
  console.log("=".repeat(65));

  // Format prompt with variables
  const formattedMessages = await promptTemplate.formatMessages({
    domain: "Software Engineering",
    targetLanguage: "Spanish",
    textToTranslate: "We need to refactor the database connection pool.",
  });

  console.log("\n--- Formatted Chat Messages Generated by Template ---");
  formattedMessages.forEach((msg) => {
    console.log(`[${msg._getType().toUpperCase()}]: ${msg.content}`);
  });

  // --- 3. Simulated Model Call (Standalone Runnable) ---
  class SimulatedChatModel {
    async invoke(messages) {
      const userPrompt = messages[messages.length - 1].content;
      return new AIMessage({
        content: `[Simulated Model Output]: Tenemos que refactorizar el grupo de conexiones a la base de datos.`,
      });
    }
  }

  const model = new SimulatedChatModel();
  console.log("\n--- Invoking Chat Model with Formatted Prompt ---");
  const response = await model.invoke(formattedMessages);
  console.log(`Model Output:\n${response.content}`);
}

main().catch(console.error);
